language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.4.1
notifications:
  email:
    recipients:
    - vespira@gmail.com
    - qpsk31@gmail.com
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-cassandra.gemspec
- gem install sensu-plugins-cassandra-*.gem
before_deploy:
  - bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: NEJgqUUESQiGwAIVKDLbpW9gR9zWwaJ9Mm8fPn7zh8gGrfUcmGT3t/NiK3xn/2f7OQDm34YxiVk+z4N90fSGB/SgLraTXzTHDWc8eyLpeCkqeotn/OeBbQ7M4mJNRtR/2nENhvbXhp3IDbzSAR8TzUyIp5junan4NbPOC2+Hms8=
  gem: sensu-plugins-cassandra
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: zenmetsu/sensu-plugins-cassandra
- provider: script
  script: chmod +x bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh && bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-cassandra-checks
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
